### ISSUE TITLE
Swiper getting crashed

### ISSUE THREAD

**Issue by SupriyaGo** [reactrondev/react-native-web-swiper#31] opened 2019-11-08 06:48 UTC
When I am adding more than 6 components inside the swiper in my app, it's getting slower and the app getting crashed. Please help.

**Comment by oxyii** [comment] 2019-11-08 10:54
@SupriyaGo looks like a memory overflow. I don’t think that the cause of the crash is the swiper exactly. What kind of content in the swiper? if these are images, have you optimized them?
try to display all your content inside a `ScrollView`.

**Comment by SupriyaGo** [comment] 2019-11-09 02:46
I have images and videos as content. yes I have optimized them by size. Where to write ScrollView?

<Swiper
  <ScrollView>
     <Component1/>
     <Component2/>
     <Component3/>
     <Component4/>
  <ScrollView/>
<Swiper/>

like this?

**Comment by oxyii** [comment] 2019-11-09 10:35
@SupriyaGo Nope. ScrollView instead Swiper. Will it crash?

**Comment by SupriyaGo** [comment] 2019-11-23 16:00
If I use ScrollView instead of a swiper, it will work like a normal scrollable page. I want a swipeable interface.

**Comment by jarvisluong** [comment] 2020-07-26 10:41
He is asking if using ScrollView also crashes your app. It is so that we can understand whether the crash is from the package or just because your components are too complex.

**Comment by jarvisluong** [comment] 2021-02-08 20:48
Hi! I'm closing this issue since there is no update in the last 90 days! Feel free to create a new issue if needed.

**Closed by jarvisluong** 2021-02-08 20:48 UTC
